plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    alias forge.plugins.modDevGradle
}

group = maven_group
version = "${mod_version}"

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

sourceSets {
    main.resources {
        srcDir 'src/generated/resources'
    }
}

legacyForge {
    // Forge 版本（GTM 同款 47.4.0）
    version = forge.versions.minecraftForge.get()

    parchment {
        minecraftVersion = forge.versions.minecraft.get()
        mappingsVersion = forge.versions.parchment.get()
    }

    addModdingDependenciesTo(sourceSets.test)

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        client {
            client()
            ideName = "Client"

            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            ideName = "Server"

            gameDirectory.set(file('run/server'))
            programArgument '--nogui'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            ideName = "Data Generation"

            gameDirectory.set(file('run/data'))
            programArguments.addAll('--mod', project.mod_id)
            programArguments.addAll('--all')
            programArguments.addAll('--output', file('src/generated/resources/').getAbsolutePath())
            programArguments.addAll('--existing', file('src/main/resources/').getAbsolutePath())
        }

        gameTestServer {
            type = "gameTestServer"
            ideName = "Game Tests"

            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.INFO
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs << "-Xlint:-removal"
}

jar {
    manifest {
        attributes([
            'Specification-Title'   : 'gtsn-terrain',
            'Specification-Vendor'  : 'GTSN',
            'Specification-Version' : '1',
            'Implementation-Title'  : 'gtsn-terrain',
            'Implementation-Version': project.jar.archiveVersion,
            'Implementation-Vendor' : 'GTSN'
        ])
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven { url "file://${project.projectDir}/mcmodsrepo" }
    }
}
