pluginManagement {
    repositories {
        maven { url = "https://maven.minecraftforge.net/" }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        mavenLocal()
    }
    versionCatalogs {
        forge {
            from(files("gradle/forge.versions.toml"))
        }
    }
}

rootProject.name = "${mod_id}"
