[versions]
minecraft = "1.20.1"
forge = "47.4.0"
minecraftForge = "1.20.1-47.4.0"
parchment = "2023.09.03"
modDevGradle = "2.0.86"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
minecraftForge = { module = "net.minecraftforge:forge", version.ref = "minecraftForge" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev.legacyforge", version.ref = "modDevGradle" }
